#!/bin/bash

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

results=$(python -m black --diff .)

# Print colorized error messages.
if [ ! -z "${results}" ]; then
    needed_changes=1
    echo -e "\n\033[31mChanges in ${changed_file} require formatting:\033[0m\n${results}" \
        | sed "s/^\(+ .*\)$/${esc}[32m\\1${esc}[0m/" \
        | sed "s/^\(- .*\)$/${esc}[31m\\1${esc}[0m/"
fi