version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    pre_create_environment:
      - ASDF_POETRY_INSTALL_URL=https://install.python-poetry.org
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry self update --preview
      - poetry config virtualenvs.create false
    post_install:
      - poetry install

sphinx:
  fail_on_warning: true

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
      extra_requirements:
         - docs