version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  # See https://github.com/readthedocs/readthedocs.org/issues/4912
  jobs:
    pre_create_environment:
      - run: |
          python -m pip install --upgrade pip
          pip install --user poetry==1.2.0b1
          poetry config virtualenvs.create false
    post_install:
      - run: |
          poetry install

sphinx:
  fail_on_warning: true

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .