version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  # See https://github.com/readthedocs/readthedocs.org/issues/4912
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry --version
      - poetry config virtualenvs.create false
    post_install:
      - poetry install

sphinx:
  fail_on_warning: true

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .