version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    pre_create_environment:
      - curl -sSL https://install.python-poetry.org | python3.9 -
      - source ~/.bash_profile
      - poetry self update --preview
      - poetry config virtualenvs.create false
      - asdf global poetry system
    post_install:
      - poetry install

sphinx:
  fail_on_warning: true

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
      extra_requirements:
         - docs