name: Continuous Integration

on: [ pull_request ]

jobs:
  test:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 30  # min
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user poetry
          poetry install
      - name: Check format
        run: |
          ./scripts/check_format.sh
      - name: Run tests
        run: |
          poetry run pytest .
