name: Release dev version

on:
  push:
    branches:
      - main

jobs:
  push_to_pypi:
    if: github.repository == 'google/qhbm-library'
    name: push_to_pypi
    runs-on: ubuntu-20.04
    env:
      NAME: dev-release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user poetry
          poetry install
      - name: Build and publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi "$PYPI_TOKEN"
          poetry version $(poetry version --short).dev$(date +%Y%m%d%H%M%S)
          poetry publish --build
